:r ./PostDeploy/dbo.Ships.Table.sql
:r ./PostDeploy/dbo.Units.Table.sql
:r ./PostDeploy/dbo.UnitAliases.Table.sql
:r ./PostDeploy/dbo.UnitEvolutions.Table.sql
:r ./PostDeploy/dbo.Stages.Table.sql
:r ./PostDeploy/dbo.StageAliases.Table.sql
:r ./PostDeploy/dbo.GCRStages.Table.sql
:r ./PostDeploy/dbo.GCRUnits.Table.sql
:r ./PostDeploy/AuthData.sql
