export function configure(config) {
    config.globalResources([
        './alert-area',
        './loading-area',
        './number-dropdown',
        './search-pager',
        './ship-display',
        './socket-display',
        './sort-buttons',
        './stage-display',
        './stage-search',
        './stage-type-picker',
        './team-box',
        './team-display',
        './team-inline',
        './team-reports',
        './team-search',
        './team-slot',
        './unit-class-picker',
        './unit-display',
        './unit-search',
        './unit-type-picker'
    ]);
}