INSERT INTO [const].[Types]([Name])VALUES(N'STR')
INSERT INTO [const].[Types]([Name])VALUES(N'DEX')
INSERT INTO [const].[Types]([Name])VALUES(N'QCK')
INSERT INTO [const].[Types]([Name])VALUES(N'INT')
INSERT INTO [const].[Types]([Name])VALUES(N'PSY')
GO
INSERT INTO [const].[Classes] ([Name]) VALUES (N'Shooter')
INSERT INTO [const].[Classes] ([Name]) VALUES (N'Fighter')
INSERT INTO [const].[Classes] ([Name]) VALUES (N'Striker')
INSERT INTO [const].[Classes] ([Name]) VALUES (N'Slasher')
INSERT INTO [const].[Classes] ([Name]) VALUES (N'Cerebral')
INSERT INTO [const].[Classes] ([Name]) VALUES (N'Driven')
INSERT INTO [const].[Classes] ([Name]) VALUES (N'Free Spirit')
INSERT INTO [const].[Classes] ([Name]) VALUES (N'Powerhouse')
GO