INSERT [dbo].[Ships] ([Id], [Name]) VALUES (0, N'Dinghy')
INSERT [dbo].[Ships] ([Id], [Name]) VALUES (1, N'Merry Go')
INSERT [dbo].[Ships] ([Id], [Name]) VALUES (2, N'Navy Ship')
INSERT [dbo].[Ships] ([Id], [Name]) VALUES (3, N'Baratie')
INSERT [dbo].[Ships] ([Id], [Name]) VALUES (4, N'Coffin Boat')
INSERT [dbo].[Ships] ([Id], [Name]) VALUES (5, N'Miss Love Duck')
INSERT [dbo].[Ships] ([Id], [Name]) VALUES (6, N'Merry Go Flying')
INSERT [dbo].[Ships] ([Id], [Name]) VALUES (7, N'Moby Dick')
INSERT [dbo].[Ships] ([Id], [Name]) VALUES (8, N'Big Top')
INSERT [dbo].[Ships] ([Id], [Name]) VALUES (9, N'Bezan Black')
INSERT [dbo].[Ships] ([Id], [Name]) VALUES (10, N'Aokiji''s Bike')
INSERT [dbo].[Ships] ([Id], [Name]) VALUES (11, N'Ace''s Striker')
INSERT [dbo].[Ships] ([Id], [Name]) VALUES (12, N'Dreadnaught Sabre')
INSERT [dbo].[Ships] ([Id], [Name]) VALUES (13, N'Thousand Sunny')
INSERT [dbo].[Ships] ([Id], [Name]) VALUES (14, N'Kuja Pirate Ship')
INSERT [dbo].[Ships] ([Id], [Name]) VALUES (15, N'Ark Maxim')
INSERT [dbo].[Ships] ([Id], [Name]) VALUES (16, N'Red Force')
INSERT [dbo].[Ships] ([Id], [Name]) VALUES (17, N'2nd Anniversary Thousand Sunny')
INSERT [dbo].[Ships] ([Id], [Name]) VALUES (18, N'Sun Pirates Ship')
INSERT [dbo].[Ships] ([Id], [Name]) VALUES (19, N'Doflamingo Ship')
INSERT [dbo].[Ships] ([Id], [Name]) VALUES (20, N'Doflamingo Ship - Special ACTIVATED')
INSERT [dbo].[Ships] ([Id], [Name]) VALUES (21, N'The Rocket Man')
INSERT [dbo].[Ships] ([Id], [Name]) VALUES (22, N'Burning Whitebeard Ship')
INSERT [dbo].[Ships] ([Id], [Name]) VALUES (23, N'Garp Ship')
INSERT [dbo].[Ships] ([Id], [Name]) VALUES (24, N'Polar Tang')
INSERT [dbo].[Ships] ([Id], [Name]) VALUES (25, N'New Year''s Big Top')
INSERT [dbo].[Ships] ([Id], [Name]) VALUES (26, N'Thousand Sunny: Coated')
INSERT [dbo].[Ships] ([Id], [Name]) VALUES (27, N'Kizaru''s Cannonball')
INSERT [dbo].[Ships] ([Id], [Name]) VALUES (28, N'Going Luffy SENPAI!')
INSERT [dbo].[Ships] ([Id], [Name]) VALUES (29, N'Thriller Bark')
INSERT [dbo].[Ships] ([Id], [Name]) VALUES (30, N'Karasumaru Ship')
INSERT [dbo].[Ships] ([Id], [Name]) VALUES (31, N'3rd Anniversary Thousand Sunny')
