INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (1001, N'Fushia Village', NULL, 1, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (1002, N'Alvida''s Hideout', NULL, 1, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (1003, N'Shells Town', NULL, 1, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (1004, N'Orange Town', NULL, 1, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (1005, N'Syrup Village', NULL, 1, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (1006, N'Baratie', NULL, 1, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (1007, N'Arlong Park', NULL, 1, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (1008, N'Logue Town', NULL, 1, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (1009, N'Twin Cape', NULL, 1, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (1010, N'Whiskey Peak', NULL, 1, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (1011, N'Little Garden', NULL, 1, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (1012, N'Drum Island', NULL, 1, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (1013, N'Nanohana - Rainbase', NULL, 1, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (1014, N'Alubarna', NULL, 1, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (1015, N'Jaya', NULL, 1, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (1016, N'Sky Island: Angel Island - Upper Yard', NULL, 1, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (1017, N'Sky Island: Upper Yard - Ark Maxim', NULL, 1, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (1018, N'Long Ring Long Land', NULL, 1, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (1019, N'Water Seven', NULL, 1, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (1020, N'Enies Lobby: Entrance', NULL, 1, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (1021, N'Enies Lobby: Tower of Justice - Gates of Justice', NULL, 1, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (1022, N'Thriller Bark: Mouth Gate - Hogback''s Residence', NULL, 1, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (1023, N'Thriller Bark: Moria''s Mast Mansion', NULL, 1, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (1024, N'Sabaody Archipelago', NULL, 1, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (1025, N'Amazon Lily', NULL, 1, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (1026, N'Impel Down', NULL, 1, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (1027, N'Marineford Bay', NULL, 1, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (1028, N'Marineford - Oris Plaza', NULL, 1, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (1029, N'3D2Y - Timeskip Training', NULL, 1, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (1030, N'Return to Sabaody Archipelago', NULL, 1, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (1031, N'Hard-Shell Tower - Dragon Imperial Palace', NULL, 1, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (1032, N'King Neptune''s Execution Site - Noah''s Ark', NULL, 1, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2001, N'Buggy''s Counterattack!!', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2002, N'Alvida''s Romance', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2003, N'Kuro''s Master Plan', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2004, N'Arlong: Empire Rising', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2005, N'Krieg''s Assault!', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2006, N'Escaped! Morgan', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2007, N'Hina''s Resort Getaway', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2008, N'Cobymeppo''s Proving Ground!', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2009, N'Smoker''s Great Pursuit', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2010, N'Tsuru''s Morning Stroll', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2011, N'Kalifa''s Secret Assignment', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2012, N'Lucci''s Artisan Spirit', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2013, N'Franky - Pervert''s Aesthetic!', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2014, N'Deep Sea Kraken', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2015, N'Dr. Hogback''s Lab of the Dead', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2016, N'Perona''s Worden Garden', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2017, N'Perv-salom''s Manly Adventure', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2018, N'Rising Sun, Rising Fortunes', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2019, N'Adrift!? Humming Brook', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2020, N'Maiden in Love - First Sight', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2021, N'Supersonic Duck Squadron!', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2022, N'Prison Break! Baroque Works', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2023, N'Crocodile: Life on the Inside', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2024, N'Jailer Domino'' Special Guard', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2025, N'Chief Jailer Sadie: Cruel and Unusual', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2026, N'Brother Soul! Afro Luffy!', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2027, N'Warriors of Shandia! Dreams of a Homeland!', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2028, N'Pirate Apprentices! Shanks and Buggy', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2029, N'Raging Cook! Red Leg Zeff', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2030, N'Camie and Hachi''s Takoyaki Shop!', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2031, N'Shark Attack! Arlong Pirates', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2032, N'Fight! Sand-Sand Band!!', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2033, N'Led by the Light of Shandora! Calgara & Noland!', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2034, N'Sky Night Ganfor', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2035, N'T-Bone''s Absolute Justice', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2036, N'Explosive! Wanze''s Ramen Kenpo!!', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2037, N'Twilight Party DEAD or TREAT!!', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2038, N'Midnight Party DEAD or TREAT!!', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2039, N'Evil Manager Breed''s Marine Circus!', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2040, N'Nami and Lola''s Great Proposal Plan', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2041, N'Legendary Shipbuilding Company Tom''s Workers', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2042, N'Wapol''s Counterattack', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2043, N'Lightning Speed! Strawhat Crew''s Surprise Visit', NULL, 2, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2044, N'Riverside Banquet! Enter the Crazy Ones!', NULL, 2, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2045, N'Mountaintop Banquet! Enter the Generals!', NULL, 2, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2046, N'Men are Forbidden!? The Secret Flower Garden', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2047, N'Hannyabal''s Great Ambition', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2048, N'Encounter! Whitebeard Pirates', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2049, N'Clash! Whitebeard Pirates', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2050, N'Let''s Find Our Captain! Heart Pirates!', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2051, N'Rare Animal Island''s Count Butler', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2052, N'Temptation!? The Queen of Kamabakka Queendom!', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2053, N'The One Who Seeks the Truth of History: Archaeologist Nico Olvia', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2054, N'Pirate Ship Competition! "Dead End" Opens!', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2055, N'Dr. Indigo & Scarlet!', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2056, N'Robin and Nami''s Secret Undercover Investigation', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2057, N'Behind the Scenes Intelligency Agency, CP9', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2058, N'Welcome To The Gran Tesoro!', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2059, N'Rumbar Pirates!', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2060, N'World Pirates!', NULL, 2, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2061, N'Revolutionary Armed Forces!', NULL, 2, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2062, N'Gather! Whitebeard Alliance', NULL, 2, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2063, N'Young Donquixote Pirates - Baby 5 And Buffalo', NULL, 2, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2064, N'Jailbreak Battle! Mr. 3 and Buggy', NULL, 2, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2065, N'Tontatta Kingdom Island Part 1: Leo', NULL, 2, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2066, N'Tontatta Kingdom Island Part 2: Mansherry', NULL, 2, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2067, N'Big Mom Pirates!', NULL, 2, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2068, N'Soldier-san''s Training!', NULL, 2, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2069, N'Shambles! Tashigi and Smoker?!?', NULL, 2, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2070, N'Marines! Sengoku the Fleet Admiral!', NULL, 2, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2071, N'Chinjao Family! The 13th Leader Appears!', NULL, 2, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2072, N'Fugitive of Love and Passion!!', NULL, 2, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2073, N'Gatekeeper of the New World! Stop the Rookies!', NULL, 2, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2074, N'Exit! Whitebeard Pirates', NULL, 2, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2075, N'Dadan Family! Encounter with the Mountain Bandits', NULL, 2, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2076, N'Soul King! Farewell Tour Concert', NULL, 2, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2077, N'Prodence Kingdom', NULL, 2, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (2078, N'Punk Hazard', NULL, 2, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (3001, N'Rush of Turtles', NULL, 3, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (3002, N'Princess Turtle''s Dragon Palace', NULL, 3, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (3003, N'Sea Pony Paradise', NULL, 3, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (3004, N'Penguin Beach', NULL, 3, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (3005, N'Penguin Long Beach', NULL, 3, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (3006, N'Dragon Sanctuary', NULL, 3, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (3007, N'Scissor Cavern', NULL, 3, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (3008, N'Scissor Cavern, Inner Cave', NULL, 3, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (3009, N'Scissor Cavern, Deepest Parts', NULL, 3, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (3010, N'Jeweled Porc Sanctuary', NULL, 3, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (4001, N'Clash!! Mihawk', NULL, 4, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (4002, N'Clash!! Chopper''s Rampage', NULL, 4, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (4003, N'Clash!! Vice-Admiral Garp', NULL, 4, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (4004, N'Clash!! Black Arm Zephyr', NULL, 4, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (4005, N'Clash!! Ivankov', NULL, 4, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (4006, N'Clash!! Doflamingo', NULL, 4, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (4007, N'Clash!! Blackbeard', NULL, 4, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (4008, N'Clash!? Usopp''n', NULL, 4, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (4009, N'Clash!! Heracles''n', NULL, 4, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (4010, N'Clash!! Aokiji', NULL, 4, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (4011, N'Clash!! Eneru', NULL, 4, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (4012, N'Clash!! Duval', NULL, 4, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (4013, N'Clash!! Buster Call', NULL, 4, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (4014, N'Clash!! Nightmare Luffy', NULL, 4, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (4015, N'Clash!! Tyrant Kuma', NULL, 4, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (4016, N'Clash!! Pirate Empress Hancock', NULL, 4, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (4017, N'Clash!! Pica', NULL, 4, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (4018, N'Clash!! Kizaru', NULL, 4, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (4019, N'Clash!? Impostor Straw Hat Pirates', NULL, 4, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (4020, N'Clash!! Sabo', NULL, 4, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (4021, N'Clash!! Shiki', NULL, 4, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (4022, N'Clash!! Gild Tesoro', NULL, 4, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (4023, N'Clash!! Akainu', NULL, 4, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (4024, N'Clash!! Warden Magellan', NULL, 4, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (4025, N'Clash!! Shogun Franky', NULL, 4, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (4026, N'Clash!! Bellamy', NULL, 4, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5001, N'Coliseum: Lucky Roo', NULL, 5, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5002, N'Coliseum: Rebecca, Imprisoned Swordsman', NULL, 5, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5003, N'Coliseum: Hina, Navy HQ Captain', NULL, 5, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5004, N'Coliseum: Wyper, Shandian Warrior', NULL, 5, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5005, N'Coliseum: Mr. 7 and Ms. Father''s Day', NULL, 5, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5006, N'Coliseum: Coby, Navy HQ Petty Officer', NULL, 5, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5007, N'Coliseum: Lady Alvida, Lovely Beauty', NULL, 5, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5008, N'Coliseum: Dorry, Giant Warrior Pirates', NULL, 5, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5009, N'Coliseum: Broggy, Giant Warrior Pirates', NULL, 5, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5010, N'Coliseum: Yokozuna', NULL, 5, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5011, N'Coliseum: Secuurity Chief Miss Sadie', NULL, 5, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5012, N'Coliseum: Doberman, Navy HQ Vice Admiral', NULL, 5, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5013, N'Coliseum: Ben Beckman', NULL, 5, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5014, N'Coliseum: Paulie Galley-La Company Dock One Foreman', NULL, 5, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5015, N'Coliseum: Brownbeard', NULL, 5, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5016, N'Coliseum: Peeply Lulu Galley-La Company Dock One Foreman ', NULL, 5, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5017, N'Coliseum: Ohm, Sky Breeder', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5018, N'Coliseum: Oars Jr.', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5019, N'Coliseum: ''Bohemian Knight'' Doma, Subordinates of the Whitebeard Pirates', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5020, N'Coliseum: ''Sky Rider'' Shura', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5021, N'Coliseum: Boa Sandersonia, Kuja Warrior', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5022, N'Coliseum: Boa Marigold, Kuja Warrior', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5023, N'Coliseum: Tony Tony Chopper Jump Point', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5024, N'Coliseum: Gedatsu, Skypean Priest', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5025, N'Coliseum: Marguerite, Amazon Lily Archer', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5026, N'Coliseum: Coliseum Dalton', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5027, N'Coliseum: T-Bone, Navy HQ Colonel', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5028, N'Coliseum: Gin, Krieg Pirates Combat Commander', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5029, N'Coliseum: Klahadore the Butler', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5030, N'Coliseum: Miss Valentine, Kilo Human', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5031, N'Coliseum: Don Krieg, Krieg Pirates Fleet Admiral', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5032, N'Coliseum: Mr. 5, Bomb Human', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5033, N'Coliseum: Arlong, Arlong Pirates Captain', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5034, N'Coliseum: Blenheim, Whitebeard 9th Div. Commander', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5035, N'Coliseum: Hajrudin, Elbaf Warriors ''New Generation''', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5036, N'Coliseum: Urouge, Fallen Monk Pirates Captain', NULL, 5, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5037, N'Coliseum: Smoker, Navy HQ Captain', NULL, 5, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5038, N'Coliseum: Basil Hawkins, Hawkins Pirates Captain', NULL, 5, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5039, N'Coliseum: Scratchmen Apoo, Captain of the On Air Pirates', NULL, 5, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5040, N'Coliseum: Fresh Franky, Health Comes First', NULL, 5, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5041, N'Coliseum: Captain Kid of the South Blue', NULL, 5, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5042, N'Coliseum: Ace, Whitebeard 2nd Div. Commander', NULL, 5, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5043, N'Coliseum: Vista Whitebeard 5th Div. Commander', NULL, 5, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5044, N'Coliseum: Capone Bege, Captain of the Firetank Pirates', NULL, 5, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5045, N'Coliseum: Jozu Whitebeard 3rd Div. Commander', NULL, 5, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5046, N'Coliseum: Killer, Kid Pirates', NULL, 5, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5047, N'Coliseum: Musshuru', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5048, N'Coliseum: Saga', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5049, N'Coliseum: X Drake, Captain of the Drake Pirates', NULL, 5, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5050, N'Coliseum: Black Arm Zephyr', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5051, N'Coliseum: Ain, NEO Marines', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5052, N'Coliseum: Binz, NEO Marines', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5053, N'Coliseum: Gecko Moria, Lord of Florian Triangle', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5054, N'Coliseum: Foxy, Nuisance of Donut Race', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5055, N'Coliseum: Porche, Flower Cheerleader', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5056, N'Coliseum: Ganfor, Former God of Skypiea', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5057, N'Coliseum: Byrnndi World', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5058, N'Coliseum: Marco, Whitebeard Pirates', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5059, N'Coliseum: Lao G, Jio-Ken User', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5060, N'Coliseum: Kinemon', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5061, N'Coliseum: Kanjuro', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5062, N'Coliseum: Dellinger, Blood Thirsty Half-Fishman Fighting Fish', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5063, N'Coliseum: Gladius, Pop-Pop Man', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5064, N'Coliseum: Diamante, Ripple-Ripple Man', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5065, N'Coliseum: Don Chinjao, Happo Navy', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5066, N'Coliseum: Ideo, XXX Rank Boxer', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5067, N'Coliseum: Suleiman the Beheader, Battle of Dias Class-A War Criminal', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (5068, N'Coliseum: Ryuma, Samurai General Zombie', NULL, 5, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (6001, N'Chopper''s Sweet Special Adventure', NULL, 6, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (6002, N'Battle Royal! Oars', NULL, 6, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (6003, N'Girls of Summer Paradise', NULL, 6, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (6004, N'Halloween Event Characters', NULL, 6, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (6005, N'Valentines Day and White Day Characters', NULL, 6, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (6006, N'2nd Anniversary Celebration! Duel! Ace', NULL, 6, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (6007, N'Rescue Ace Event - Akainu', NULL, 6, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (6008, N'Rescue Ace Event - Aokiji', NULL, 6, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (6009, N'Rescue Ace Event - Kizaru', NULL, 6, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (6010, N'Invasion! Young Whitebeard', NULL, 6, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (6011, N'Invasion! Red Hair Shanks', NULL, 6, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (6012, N'Invasion! Cavendish', NULL, 6, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (6013, N'The Flashback Before the Reunion! Fight all your Enemies!', NULL, 6, 0, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (7001, N'Mihawk Training Forest', NULL, 7, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (7002, N'Whitebeard Training Forest', NULL, 7, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (7003, N'Aokiji Training Forest', NULL, 7, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (7004, N'Ace Training Forest', NULL, 7, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (7005, N'Jimbe Training Forest', NULL, 7, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (7006, N'Enel Training Forest', NULL, 7, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (7007, N'Shanks Training Forest', NULL, 7, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (7008, N'Boa Training Forest', NULL, 7, 1, NULL)
INSERT [dbo].[Stages] ([Id], [Name], [Stamina], [Type], [Global], [ParentId]) VALUES (7009, N'Doflamingo Training Forest', NULL, 7, 1, NULL)
