//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureGuide.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public decimal Amount { get; set; }
        public string Message { get; set; }
        public System.DateTimeOffset Date { get; set; }
        public PaymentState State { get; set; }
        public PaymentType PaymentType { get; set; }
        public string PaymentId { get; set; }
        public string PayerId { get; set; }
        public Nullable<bool> Public { get; set; }
        public string TokenId { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
