//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureGuide.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCRTable
    {
        public int Id { get; set; }
        public Nullable<int> LeaderId { get; set; }
        public string LeaderName { get; set; }
        public Nullable<UnitType> LeaderColor { get; set; }
        public Nullable<int> StageId { get; set; }
        public Nullable<int> StageThumb { get; set; }
        public string StageName { get; set; }
        public Nullable<UnitType> StageColor { get; set; }
        public Nullable<bool> F2P { get; set; }
        public Nullable<bool> Global { get; set; }
        public Nullable<bool> Video { get; set; }
    }
}
