//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureGuide.Entities
{
    using System;
    
    public enum IndividualUnitFlags : int
    {
        Unknown = 0,
        Favorite = 32,
        LevelMaxed = 1,
        SkillLevelMaxed = 2,
        SocketsMaxed = 4,
        CottonCandyMaxed = 8,
        LimitBroken = 16
    }
}
