//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureGuide.Entities
{
    using System;
    
    public enum NotificationEventType : int
    {
        Unknown = 0,
        TeamComment = 1,
        CommentReply = 2,
        TeamVideo = 3
    }
}
