//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureGuide.Entities
{
    using System;
    
    public enum PaymentState : byte
    {
        Unknown = 0,
        Initialized = 1,
        Processing = 2,
        Complete = 3,
        Failed = 4,
        Cancelled = 5,
        Chargeback = 6
    }
}
