//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureGuide.Entities
{
    using System;
    
    public enum SocketType : byte
    {
        DamageReduction = 0,
        ChargeSpecials = 1,
        BindResistance = 2,
        DespairResistance = 3,
        AutoHeal = 4,
        RCVBoost = 5,
        SlotRateBoost = 6,
        PoisonResistance = 7,
        MapDamageResistance = 8,
        Resilience = 9
    }
}
