//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureGuide.Entities
{
    using System;
    
    public enum SocketType : byte
    {
        Unknown = 0,
        DamageReduction = 1,
        ChargeSpecials = 2,
        BindResistance = 3,
        DespairResistance = 4,
        AutoHeal = 5,
        RCVBoost = 6,
        SlotRateBoost = 7,
        PoisonResistance = 8,
        MapDamageResistance = 9,
        Resilience = 10
    }
}
