//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureGuide.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StageUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StageUnit()
        {
            this.StageUnitAttackPatterns = new HashSet<StageUnitAttackPattern>();
        }
    
        public int Id { get; set; }
        public int StageLevelId { get; set; }
        public int UnitId { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<short> HP { get; set; }
        public Nullable<short> Defense { get; set; }
        public Nullable<short> ATK { get; set; }
        public Nullable<byte> MinCD { get; set; }
        public Nullable<byte> MaxCD { get; set; }
        public Nullable<byte> Interval { get; set; }
    
        public virtual StageLevel StageLevel { get; set; }
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StageUnitAttackPattern> StageUnitAttackPatterns { get; set; }
    }
}
