//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureGuide.Entities
{
    using System;
    
    public enum StageType : byte
    {
        Story = 0,
        Fortnight = 1,
        Weekly = 2,
        Raid = 3,
        Coliseum = 4,
        Special = 5
    }
}
