//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureGuide.Entities
{
    using System;
    
    public enum StageType : byte
    {
        Unknown = 0,
        Story = 1,
        Fortnight = 2,
        Weekly = 3,
        Raid = 4,
        Coliseum = 5,
        Special = 6,
        TrainingForest = 7
    }
}
