//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureGuide.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeamComment()
        {
            this.TeamCommentVotes = new HashSet<TeamCommentVote>();
            this.Children = new HashSet<TeamComment>();
        }
    
        public int Id { get; set; }
        public int TeamId { get; set; }
        public string Text { get; set; }
        public bool Deleted { get; set; }
        public bool Reported { get; set; }
        public string SubmittedById { get; set; }
        public System.DateTimeOffset SubmittedDate { get; set; }
        public string EditedById { get; set; }
        public System.DateTimeOffset EditedDate { get; set; }
        public int Version { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        public virtual UserProfile EditedBy { get; set; }
        public virtual UserProfile SubmittedBy { get; set; }
        public virtual Team Team { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamCommentVote> TeamCommentVotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamComment> Children { get; set; }
        public virtual TeamComment Parent { get; set; }
        public virtual TeamCommentScore TeamCommentScore { get; set; }
    }
}
