//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureGuide.Entities
{
    using System;
    
    public enum TeamCreditType : short
    {
        Unknown = 0,
        Reddit = 1,
        YouTube = 2,
        Twitter = 3,
        Slefty = 4,
        Irving = 5
    }
}
