//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureGuide.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamReport
    {
        public int Id { get; set; }
        public int TeamId { get; set; }
        public string Reason { get; set; }
        public System.DateTimeOffset SubmittedDate { get; set; }
        public Nullable<System.DateTimeOffset> AcknowledgedDate { get; set; }
    
        public virtual Team Team { get; set; }
    }
}
