//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureGuide.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamCredit
    {
        public int TeamId { get; set; }
        public string Credit { get; set; }
        public TeamCreditType Type { get; set; }
    
        public virtual Team Team { get; set; }
    }
}
