//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureGuide.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamMini
    {
        public int TeamId { get; set; }
        public string Name { get; set; }
        public Nullable<int> StageId { get; set; }
        public string StageName { get; set; }
        public Nullable<int> InvasionId { get; set; }
        public string InvasionName { get; set; }
        public bool EventShip { get; set; }
        public string SubmittedById { get; set; }
        public string SubmittingUserName { get; set; }
        public bool Draft { get; set; }
        public bool Deleted { get; set; }
        public bool HasReport { get; set; }
        public bool Global { get; set; }
        public bool F2P { get; set; }
        public bool F2PC { get; set; }
        public UnitType Type { get; set; }
        public UnitClass Class { get; set; }
        public Nullable<int> HelperId { get; set; }
        public Nullable<int> LeaderId { get; set; }
        public bool HasSupports { get; set; }
    
        public virtual Stage Stage { get; set; }
        public virtual Stage Invasion { get; set; }
        public virtual Team Team { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual Unit Helper { get; set; }
        public virtual Unit Leader { get; set; }
    }
}
