//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureGuide.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamCommentVote
    {
        public int TeamCommentId { get; set; }
        public string UserId { get; set; }
        public System.DateTimeOffset SubmittedDate { get; set; }
        public short Value { get; set; }
    
        public virtual TeamComment TeamComment { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
