//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureGuide.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamGenericSlot
    {
        public int TeamId { get; set; }
        public byte Position { get; set; }
        public Nullable<UnitType> Type { get; set; }
        public Nullable<UnitClass> Class { get; set; }
        public Nullable<UnitRole> Role { get; set; }
        public Nullable<byte> Combo { get; set; }
    
        public virtual Team Team { get; set; }
    }
}
