//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureGuide.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Team()
        {
            this.TeamUnits = new HashSet<TeamUnit>();
        }
    
        public int Id { get; set; }
        public int StageDifficultyId { get; set; }
        public string SubmittedById { get; set; }
        public string Description { get; set; }
        public string Credits { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual StageDifficulty StageDifficulty { get; set; }
        public virtual TeamSocket TeamSocket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamUnit> TeamUnits { get; set; }
    }
}
