//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureGuide.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    [DbConfigurationType(typeof(TreasureEntitiesConfiguration))] 
    public partial class TreasureEntities : DbContext
    {
        public TreasureEntities()
            : base("name=TreasureEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TeamSocket> TeamSockets { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<Stage> Stages { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<TeamVote> TeamVotes { get; set; }
        public virtual DbSet<TeamReport> TeamReports { get; set; }
        public virtual DbSet<TeamVideo> TeamVideos { get; set; }
        public virtual DbSet<TeamCredit> TeamCredits { get; set; }
        public virtual DbSet<UnitAlias> UnitAliases { get; set; }
        public virtual DbSet<TeamGenericSlot> TeamGenericSlots { get; set; }
        public virtual DbSet<Box> Boxes { get; set; }
        public virtual DbSet<UserPreference> UserPreferences { get; set; }
        public virtual DbSet<TeamUnit> TeamUnits { get; set; }
        public virtual DbSet<BoxUnit> BoxUnits { get; set; }
        public virtual DbSet<StageAlias> StageAliases { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Donation> Donations { get; set; }
        public virtual DbSet<UnitEvolution> UnitEvolutions { get; set; }
        public virtual DbSet<ScheduledEvent> ScheduledEvents { get; set; }
        public virtual DbSet<GCRTable> GCRTables { get; set; }
        public virtual DbSet<GCRStage> GCRStages { get; set; }
        public virtual DbSet<GCRUnit> GCRUnits { get; set; }
        public virtual DbSet<GCRStageInfo> GCRStageInfoes { get; set; }
        public virtual DbSet<GCRUnitInfo> GCRUnitInfoes { get; set; }
        public virtual DbSet<CacheSet> CacheSets { get; set; }
        public virtual DbSet<Ship> Ships { get; set; }
        public virtual DbSet<TeamComment> TeamComments { get; set; }
        public virtual DbSet<TeamCommentVote> TeamCommentVotes { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<TeamScore> TeamScores { get; set; }
        public virtual DbSet<TeamCommentScore> TeamCommentScores { get; set; }
        public virtual DbSet<TeamMini> TeamMinis { get; set; }
    
        public virtual int UpdateTeamCommentScores(Nullable<int> teamCommentId)
        {
            var teamCommentIdParameter = teamCommentId.HasValue ?
                new ObjectParameter("teamCommentId", teamCommentId) :
                new ObjectParameter("teamCommentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTeamCommentScores", teamCommentIdParameter);
        }
    
        public virtual int UpdateTeamScores(Nullable<int> teamId)
        {
            var teamIdParameter = teamId.HasValue ?
                new ObjectParameter("teamId", teamId) :
                new ObjectParameter("teamId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTeamScores", teamIdParameter);
        }
    
        public virtual int UpdateTeamMinis(Nullable<int> teamId)
        {
            var teamIdParameter = teamId.HasValue ?
                new ObjectParameter("teamId", teamId) :
                new ObjectParameter("teamId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTeamMinis", teamIdParameter);
        }
    }
}
