//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureGuide.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TreasureEntities : DbContext
    {
        public TreasureEntities()
            : base("name=TreasureEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UnitClass> UnitClasses { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<Stage> Stages { get; set; }
        public virtual DbSet<StageLevel> StageLevels { get; set; }
        public virtual DbSet<StageUnit> StageUnits { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<TeamSocket> TeamSockets { get; set; }
        public virtual DbSet<TeamUnit> TeamUnits { get; set; }
        public virtual DbSet<UnitFlag> UnitFlags { get; set; }
        public virtual DbSet<TeamVote> TeamVotes { get; set; }
        public virtual DbSet<StageDifficulty> StageDifficulties { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<StageUnitAttackPattern> StageUnitAttackPatterns { get; set; }
    }
}
