//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureGuide.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitFlags
    {
        public int UnitId { get; set; }
        public bool Global { get; set; }
        public bool RR { get; set; }
        public bool ERR { get; set; }
        public bool LRR { get; set; }
        public bool Promo { get; set; }
        public bool Shop { get; set; }
    
        public virtual Unit Unit { get; set; }
    }
}
