//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureGuide.Entities
{
    using System;
    
    [Flags]
    public enum UnitClass : short
    {
        Unknown = 0,
        Shooter = 1,
        Fighter = 2,
        Striker = 4,
        Slasher = 8,
        Cerebral = 16,
        Driven = 32,
        Powerhouse = 64,
        FreeSpirit = 128,
        Evolver = 256,
        Booster = 512
    }
}
