//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureGuide.Entities
{
    using System;
    
    [Flags]
    public enum UnitType : short
    {
        Unknown = 0,
        STR = 1,
        DEX = 2,
        QCK = 4,
        INT = 8,
        PSY = 16
    }
}
