//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureGuide.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitEvolution
    {
        public int FromUnitId { get; set; }
        public int ToUnitId { get; set; }
        public Nullable<System.DateTimeOffset> EditedDate { get; set; }
    
        public virtual Unit EvolvesFrom { get; set; }
        public virtual Unit EvolvesTo { get; set; }
    }
}
