//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureGuide.Entities
{
    using System;
    
    public enum UnitClassEnum : byte
    {
        Shooter = 0,
        Fighter = 1,
        Striker = 2,
        Slasher = 3,
        Cerebral = 4,
        Driven = 5,
        Powerhouse = 6,
        Evolver = 7,
        Booster = 8
    }
}
