//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureGuide.Entities
{
    using System;
    
    public enum UnitClassType : byte
    {
        Unknown = 0,
        Shooter = 1,
        Fighter = 2,
        Striker = 3,
        Slasher = 4,
        Cerebral = 5,
        Driven = 6,
        Powerhouse = 7,
        Evolver = 8,
        Booster = 9
    }
}
