//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureGuide.Entities
{
    using System;
    
    public enum UnitFlagTypes : byte
    {
        Global = 0,
        RareRecruit = 1,
        RareRecruitExclusive = 2,
        RareRecruitLimited = 3,
        Promotional = 4,
        Shop = 5
    }
}
