//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureGuide.Entities
{
    using System;
    
    public enum UnitTypeEnum : byte
    {
        STR = 0,
        DEX = 1,
        QCK = 2,
        INT = 3,
        PSY = 4
    }
}
