//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureGuide.Entities
{
    using System;
    
    public enum UnitFlagTypes : byte
    {
        Unknown = 0,
        Global = 1,
        RareRecruit = 2,
        RareRecruitExclusive = 3,
        RareRecruitLimited = 4,
        Promotional = 5,
        Shop = 6
    }
}
