//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureGuide.Entities
{
    using System;
    
    public enum UnitType : byte
    {
        Unknown = 0,
        STR = 1,
        DEX = 2,
        QCK = 3,
        INT = 4,
        PSY = 5
    }
}
