//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureGuide.Entities
{
    using System;
    
    [Flags]
    public enum UnitRole : int
    {
        Unknown = 0,
        Beatstick = 1,
        DamageReducer = 2,
        DefenseReducer = 4,
        Delayer = 8,
        AttackBooster = 16,
        OrbBooster = 32,
        FixedDamage = 64,
        HealthCutter = 128,
        OrbShuffler = 256,
        Healer = 512,
        Zombie = 1024,
        Nuker = 2048,
        AttackDownReducer = 4096,
        ParalysisReducer = 8192,
        DamageThresholdReducer = 16384,
        AffinityBooster = 32768,
        ChainLocker = 65536,
        BarrierReducer = 131072,
        SilenceReducer = 262144,
        BindReducer = 524288,
        BlindReducer = 1048576,
        SkillLockReducer = 2097152,
        CooldownReducer = 4194304,
        OrbLocker = 8388608,
        AdditionalDamageDealer = 16777216,
        EndOfTurnDamageReducer = 33554432
    }
}
