//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureGuide.Entities
{
    using System;
    
    [Flags]
    public enum UnitFlag : short
    {
        Unknown = 0,
        Global = 1,
        RareRecruit = 2,
        RareRecruitExclusive = 4,
        RareRecruitLimited = 8,
        Promotional = 16,
        Shop = 32
    }
}
