//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureGuide.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPreference
    {
        public string UserId { get; set; }
        public UserPreferenceType Key { get; set; }
        public string Value { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
